# ... (la parte de build-and-push no cambia) ...

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Variables
            CONTAINER_NAME="nginx-app"
            IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/nginx-technical-test:latest"
            PERSISTENT_DATA_PATH="/home/${{ secrets.EC2_USERNAME }}/app-data" # Ruta en el servidor EC2

            # Detener y eliminar el contenedor antiguo si existe
            docker stop ${CONTAINER_NAME} || true
            docker rm ${CONTAINER_NAME} || true

            # Forzar la descarga de la nueva imagen desde Docker Hub
            docker pull ${IMAGE_NAME}

            # --- ESTA ES LA LÍNEA CLAVE ---
            # Ejecutar el nuevo contenedor MONTANDO EL VOLUMEN
            docker run -d \
              -p 80:8080 \
              --name ${CONTAINER_NAME} \
              --restart always \
              -v ${PERSISTENT_DATA_PATH}:/usr/share/nginx/html/persistent_data \
              ${IMAGE_NAME}